name: tinyco

services:

  api:
    build: ./src
    image: tinyco/fastcelery:2.3
    container_name: fastapi
    command: uvicorn project.fast:app --host 0.0.0.0
    ports:
      - "8000:8000"
    volumes:
      - ./src:/usr/src/app
    depends_on:
      - redis
      - postgres

  worker-1: &worker
    image: tinyco/fastcelery:2.3
    container_name: worker-1
    command: ['celery', '-A', 'project.tasks.app', 'worker', '--pool=solo', '--concurrency=3', '--loglevel=info']
    environment:
      - WORKER_ID=${WORKER1}
    volumes:
      - ./src:/usr/src/app
    depends_on:
      - api
      - redis
      - postgres

  worker-2:
    <<: *worker
    container_name: worker-2
    environment:
      - WORKER_ID=${WORKER2}

  flower:
    image: tinyco/fastcelery:2.3
    container_name: flower
    command: ['celery', '-A', 'project.tasks.app', 'flower', '--port=5555']
    ports:
      - "5555:5555"
    depends_on:
      - api
      - redis

  redis:
    container_name: redis
    image: redis:latest
    volumes:
      - redis_data:/data/

  postgres:
    container_name: postgres
    image: postgres:15.8
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=${PGSQL_USER}
      - POSTGRES_PASSWORD=${PGSQL_PASS}
      - POSTGRES_DB=${PGSQL_DATABASE}
    ports:
      - "5432:5432"
    restart: unless-stopped

volumes:
  postgres_data:
    external: true
  redis_data:
    external: true
