name: tinyco

services:

  api:
    build: ./src
    image: tinyco/fastcelery:${BUILD_TAG:-latest}
    container_name: fastapi
    command: ['uvicorn', 'project.fast:app', '--host', '0.0.0.0']
    ports:
      - "8000:8000"
    volumes:
      - ./src:/usr/src/app
    depends_on:
      - redis
      - postgres
      - mongo

  worker-1: &worker
    image: tinyco/fastcelery:${BUILD_TAG:-latest}
    container_name: worker-1
    command: ['celery', '-A', 'project.worker.app', 'worker', '-Q', 'pool_solo,pool_any', '--pool=solo']
    environment:
      - WORKER_ID=${WORKER1}
    volumes:
      - ./src:/usr/src/app
    depends_on:
      - api
      - redis
      - postgres
      - mongo

  worker-2:
    <<: *worker
    container_name: worker-2
    environment:
      - WORKER_ID=${WORKER2}

  worker-3:
    <<: *worker
    container_name: worker-3
    command: ['celery', '-A', 'project.worker.app', 'worker', '-Q', 'pool_any', '--pool=threads']
    environment:
      - WORKER_ID=${WORKER3}

  flower:
    image: tinyco/fastcelery:${BUILD_TAG:-latest}
    container_name: flower
    command: ['celery', '-A', 'project.worker.app', 'flower', '--port=5555']
    ports:
      - "5555:5555"
    depends_on:
      - api
      - redis

  redis:
    container_name: redis
    image: redis:latest
    volumes:
      - redis_data:/data/

  postgres:
    container_name: postgres
    image: postgres:15.8
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=${PGSQL_USER}
      - POSTGRES_PASSWORD=${PGSQL_PASS}
      - POSTGRES_DB=${PGSQL_DATABASE}
    ports:
      - "5432:5432"
    restart: unless-stopped

  mongo:
    container_name: mongo
    image: mongo:8.0.1
    volumes:
      - mongo_data:/data/db
      - mongo_config:/data/configdb
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGODB_USER}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGODB_PASS}
    ports:
      - "27017:27017"
    restart: unless-stopped

volumes:
  postgres_data:
    external: true
  redis_data:
    external: true
  mongo_data:
    external: true
  mongo_config:
    external: true
